# Generated by Django 4.0.3 on 2022-08-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
