# Generated by Django 4.0.3 on 2023-08-23 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_jobdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
