# Generated by Django 4.0.3 on 2023-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_extendedauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
