# Generated by Django 4.0.3 on 2023-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobdescription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='keyword',
            field=models.TextField(null=True),
        ),
    ]
