# Generated by Django 4.0.3 on 2023-08-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_jobdescription_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
