# Generated by Django 4.0.3 on 2023-08-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='images',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='images',
            field=models.ManyToManyField(related_name='profile', to='api.image'),
        ),
    ]
