# Generated by Django 4.0.3 on 2023-08-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_userprofile_images_userprofile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='images',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.image'),
        ),
    ]
