# Generated by Django 4.0.3 on 2023-08-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
