# Generated by Django 4.0.3 on 2023-08-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_bidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='job_poster',
        ),
    ]
