# Generated by Django 4.0.3 on 2023-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
