# Generated by Django 4.0.3 on 2023-09-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='jobstatus',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.projectstatus'),
        ),
    ]
