# Generated by Django 4.0.3 on 2023-09-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_jobdescription_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
