# Generated by Django 4.0.3 on 2023-09-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_bidding_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
