# Generated by Django 4.0.3 on 2023-09-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
