# Generated by Django 4.0.3 on 2023-09-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_worker_order_job_bid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='job_bid_id',
            new_name='job_bid',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
