# Generated by Django 4.0.3 on 2023-09-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_job_bid_id_order_job_bid_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='a5f1f0b61dbf421f9d669d5575f9ea04', editable=False, max_length=32, unique=True),
        ),
    ]
