# Generated by Django 4.0.3 on 2023-09-22 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0044_cv_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='b32f8b27edd542dd9b498ec990cab6a7', editable=False, max_length=32, unique=True),
        ),
    ]
