# Generated by Django 4.0.3 on 2023-09-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_cv_author_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='501b3d9622e54d6e83ec64cdd49b384e', editable=False, max_length=32, unique=True),
        ),
    ]
