# Generated by Django 4.0.3 on 2023-09-22 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0046_rename_author_cv_user_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='2f3c175026dd466fb77d23561d5e8eaa', editable=False, max_length=32, unique=True),
        ),
    ]
