# Generated by Django 4.0.3 on 2023-09-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_cv_user_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='a3f26a45d3b2451ba82f68a1df76884c', editable=False, max_length=32, unique=True),
        ),
    ]
