# Generated by Django 4.0.3 on 2023-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_cv_keywords_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='fd6e6b350e594de5bbcb8867fac47026', editable=False, max_length=32, unique=True),
        ),
    ]
