# Generated by Django 4.0.3 on 2023-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_skills_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='cf2c5a94a5d947e9815ea6eeca68e0d1', editable=False, max_length=32, unique=True),
        ),
    ]
