# Generated by Django 4.0.3 on 2023-09-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='2fb1ed0e835b42909ad511f172ef41aa', editable=False, max_length=32, unique=True),
        ),
    ]
