# Generated by Django 4.0.3 on 2023-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='course_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='58fe13964c504b3599a5fe5ba7bbefac', editable=False, max_length=32, unique=True),
        ),
    ]
